### PR TITLE
feat: Feature/opentel

### PR DESCRIPTION
**Pull request by bearrito**
# Description
Adds in support for Open Telemetry as an exporter

- The exporter exports to opentel collectors. The exporter can natively handle any of the supported opentel exporters. However, configuration of these exporters isn't supported yet. If users wanted them I think it's feasible, it just makes configuration via relay difficult.
- The reflection code to convert `interfaces` to opentel attributes is sketchy but tested. If there is a better approach I can do that.
- Opentel really wants you to store providers as global, I think what I have is resource safe, but it's worth noting how the provider works.
- I'd like to add more serious testing with the testcontainer

# Changes include
- [+] New feature (non-breaking change that adds functionality)

# Closes issue(s)
https://github.com/thomaspoignant/go-feature-flag/issues/1375

# Checklist
- [+] I have tested this code
- [+] I have added unit test to cover this code
- [ ] I have updated the documentation (`README.md` and `/website/docs`)
- [ ] I have followed the [contributing guide](CONTRIBUTING.md)

### CODE REVIEW

**Comment by bearrito** [comment]
@thomaspoignant Can you let me know what you think of this?

Some of the more interesting spots.
1. I added in a dependency on `testcontainers-go` so that I could test out hooking into an `otel collector`
2. I wanted to use the default in memory exporter for testing, but it didn't do what I needed. I'm not sure how to handle that for this project license wise. I could get rid of the copy-paste and wrap the default one and only change the method I need.
3. Since the `Value` on `FeatureEvent` is an `interface` it was a bit tricky to get in as a set of attributes. I had to make some design decisions on how to do that.

**Comment by bearrito** [comment]
There is some issue with tc running in GHA. I opened an issue about it - https://github.com/testcontainers/testcontainers-go/issues/2507

**Comment by thomaspoignant** [comment]
I am sorry to be slow on the review. I will do it very soon.

**Comment by bearrito** [comment]
> I am sorry to be slow on the review. I will do it very soon.

No problem. Life exists outside github!

**Comment by bearrito** [comment]
@thomaspoignant Anything else on this? I'm going on holiday and am closing out my open pr's

**Comment by thomaspoignant** [comment]
Sorry I had no time to test it properly.
But don't worry we can look at it after your vacation.

**Pull request closed without merging**
