### PR TITLE
Support multi-line targeting rule in GOFF editor

### LINKED ISSUE #797: (feature) Support multiple-line targeting rule in GOFF editor
### Requirements

Given the following targeting rule, it's not easy to define the **query** part in GOFF editor because a single-line input is used currently.
```
example-flag:
  variations:
    default_var: false
    false_var: false
    true_var: true
  targeting:
    - query: |
        companyUUID IN ["4f7443e9-2f64-433d-8472-008550ca0bb9",
        "239a936b-e33b-4040-8893-1fea7ad8ad88",
        "7afa0655-59d1-4a3a-b422-f9f35d80ac0c"]
      variation: true_var
  defaultRule:
    percentage:
      false_var: 100
```
It would be really nice to have a multiple-line input for this case.

### PR DESCRIPTION
**Pull request by yangzhaox**
# Description
Support multi-line targeting rule in GOFF editor. 

# Changes include
- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking changes (change that is not backward-compatible and/or changes current functionality)

# Closes issue(s)
Resolve #797 

# Checklist
- [x] I have tested this code
- [ ] I have added unit test to cover this code
- [ ] I have updated the documentation (`README.md` and `/website/docs`)
- [x] I have followed the [contributing guide](CONTRIBUTING.md)

### CODE REVIEW

**Comment by thomaspoignant** [comment]
@yangzhaox thanks a lot for this pull request, this will probably help a lot to have a textarea instead as an input.
I haven't looked in details to the code yet, but I see some limitation while using the netlify preview.

When using `json` it adds some `\n` that will probably break the rule.
Despite that from my first check it looks good for `yaml` and `toml`

https://github.com/thomaspoignant/go-feature-flag/assets/17908063/40e04344-1610-448f-bf6f-081ebb1cc465

**Comment by yangzhaox** [comment]
In order to support multi-line text as value in JSON, it is the correct way to use `\n` to represent a new line. So this won't be a breaking change for JSON users.

**Comment by thomaspoignant** [comment]
@yangzhaox I think you can probably add a test similar to this one, with a multiline query.
 https://github.com/thomaspoignant/go-feature-flag/blob/a22560d80bf426b3f78e79f5de2ea66e2cb1459e/feature_flag_test.go#L153

**Review by thomaspoignant — APPROVED** [review]
Thanks a lot for the change.
Let's deploy it to the website 🚀

**Pull request merged**
