### PR TITLE
chore: go 1.21 migration

### PR DESCRIPTION
**Pull request by chenrui333**
# Description

- Update go.mod and go.sum for 1.17.0 release
- Bump `github.com/nikunjy/rules` to use the go `1.21.0` compatible version.

# Changes include
- [x] Bugfix (non-breaking change that solves an issue)

# Closes issue(s)

help https://github.com/Homebrew/homebrew-core/pull/153255

# Checklist
- [x] I have tested this code
- [x] I have followed the [contributing guide](CONTRIBUTING.md)

### CODE REVIEW

**Comment by thomaspoignant** [comment]
@chenrui333 I see that you have bump the version of go to 1.21.
Any reason why? Is it required by homebrew?

**Comment by chenrui333** [comment]
> @chenrui333 I see that you have bump the version of go to 1.21. Any reason why? Is it required by homebrew?

yeah, we do always build against latest go.

**Comment by chenrui333** [comment]
side note, only go1.20 and go1.21 are supported by go team atm

**Comment by thomaspoignant** [comment]
I've fixed some places where go 1.21 was used.

**Comment by chenrui333** [comment]
Thanks @thomaspoignant!

**Pull request merged**
